#### general settings
name: STEN
use_tb_logger: true
model: sr
distortion: sr
scale: 1
gpu_ids: [0,1]

#### datasets
datasets:
  train:
    name: UEN
    mode: UEN_train
    interval_list: [1]
    random_reverse: false
    border_mode: false
#    dataroot: /data/1760921465/dped/iphone/test_data/patches
    cache_keys: ~
#    filelist: /home/eescut/Desktop/ExposureNorm-Compensation/SID_ENC/data/groups_train_mixexposure.txt
    filelist: /home/wrl/DR_Datasets/fine_tune/finetune_18.txt

    use_shuffle: true
    n_workers: 0  # per GPU
    batch_size: 16
    # IN_size: 384
    IN_size: 256
    augment: true
    color: RGB

  val:
    name: UEN
    mode: UEN_test
#    dataroot: /data/1760921465/dped/iphone/test_data/patches
    filelist: /home/wrl/DR_Datasets/DIBCO2018/18.txt
    # 不设为1会报错
    batch_size: 1
    use_shuffle: false


#### network structures
network_G:
  which_model_G: SID
  nf: 16
  groups: 8

#### path
path:
  root: /home/wrl/DocNLC/output
  results_root: /home/wrl/DocNLC/output
  pretrain: /home/wrl/DocNLC/pretrain1
  pretrain_model_G: /home/wrl/DocNLC/pretrain1/Barlow/no_mse_47_G_toohighcannotuse.pth
  strict_load: false
  resume_state: 

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  # niter: 1200000
  niter: 60000
  ewc: false
  distill: true
  ewc_coff: 50.0
  distill_coff: 0.2
  fix_some_part: ~
  warmup_iter: -1  # -1: no warm up
  ComputeImportance: false
  istraining: true
#### for cosine adjustment
#  T_period: [400000, 1000000, 1500000, 1500000, 1500000]
#  restarts: [400000, 1400000, 2700000, 4200000]
#  restart_weights: [1, 1, 1, 1]
  lr_scheme: MultiStepLR
  # lr_steps: [600000, 900000]
  # lr_steps: [60, 90]
  lr_steps: [60, 90]
  lr_gamma: 0.5

  eta_min: !!float 5e-6
  pixel_criterion: l1
  pixel_weight: 5000.0
  ssim_weight: 1000.0
  vgg_weight: 1000.0

  val_epoch: !!float 1
  manual_seed: 0

#### logger
logger:
  print_freq: 40
  save_checkpoint_epoch: !!float 1
